### ISSUE TITLE
Invalid API key provided

### ISSUE THREAD

**Issue by Simoh23999** [MaxineXiong/ChatGPT-Tkinter-Desktop-App#1]
i tried different API KEYS ,but the application shows error textbox tha the api key is invalid

**Comment by Cooly75** [comment]
Same error here, any valid key do not work in application. but anyway , this program still use online data, for the ultility i need it for not very usefull

**Comment by MaxineXiong** [comment]
> Same error here, any valid key do not work in application. but anyway , this program still use online data, for the ultility i need it for not very usefull

Hi there,

Thanks for letting me know. I haven't maintained this application for almost half year so I'm really grateful for letting me know any related issues. 

I tried from my end through another API app using my secret key, and it appears to be a **Rate Limit Error** that causes the problem. So it's probably due to us not on a paid tier? 

![image](https://github.com/MaxineXiong/ChatGPT-3.5-Desktop-App/assets/55864839/eda1bf89-da32-4dbb-806b-ef4933abe178)

Don't know if your error is of the same type. I'll upgrade to see if this issue can be fixed.

Thanks

**Comment by MaxineXiong** [comment]
@Cooly75 @Simoh23999 
Hi there,

I guess the issue is mostly due to **[RateLimitError](https://platform.openai.com/docs/guides/error-codes/python-library-error-types)**. To fixe the problem, please make sure [your credit balance is not $0](https://platform.openai.com/account/billing/overview) because "When your credit balance reaches $0, your API requests will stop working", according to the [OpenAI billing page](https://platform.openai.com/account/billing/overview).



Please let me know if you have further questions.

Thanks

**Comment by Cooly75** [comment]
the problem is , openai are worthless for offline usage, i do use it in a offline network therefor unfurtunate your tool (its a great tool) are for my application worthless, i have no otherchoice as to continue to train my gpt4all and xgpt to fullfill the worktast i ask for. OpenAI ist to restrictive when it comes to fightscenes and battlefields ffmo design. thats the next reason why it is worthless for my usage.
